// Generated by jextract

package rapier.sys_dim2_f64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct RprArenaKey RprImpulseJointHandle;
 * }
 */
public final class RprImpulseJointHandle extends RprArenaKey {

    // Suppresses default constructor, ensuring non-instantiability.
    private RprImpulseJointHandle() {}
}


