name: Build FFI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dimension: [dim2, dim3]
        precision: [f32, f64]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd rapier-ffi
        cargo build --verbose --features ${{ matrix.dimension }}-${{ matrix.precision }}
    - name: Test
      run: |
        cd rapier-ffi
        cargo test --verbose --features ${{ matrix.dimension }}-${{ matrix.precision }}
