// Generated by jextract

package rapier.sys_dim2;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final FunctionDescriptor RprContactPair_collider1$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("index"),
        Constants$root.C_INT$LAYOUT.withName("generation")
    ).withName("RprArenaKey"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_collider1$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_collider1",
        constants$39.RprContactPair_collider1$FUNC
    );
    static final FunctionDescriptor RprContactPair_collider2$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("index"),
        Constants$root.C_INT$LAYOUT.withName("generation")
    ).withName("RprArenaKey"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_collider2$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_collider2",
        constants$39.RprContactPair_collider2$FUNC
    );
    static final FunctionDescriptor RprContactPair_has_any_active_contact$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_has_any_active_contact$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_has_any_active_contact",
        constants$39.RprContactPair_has_any_active_contact$FUNC
    );
    static final FunctionDescriptor RprContactPair_manifolds$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_manifolds$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_manifolds",
        constants$39.RprContactPair_manifolds$FUNC
    );
    static final FunctionDescriptor RprGenericJoint_contacts_enabled$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprGenericJoint_contacts_enabled$MH = RuntimeHelper.downcallHandle(
        "RprGenericJoint_contacts_enabled",
        constants$39.RprGenericJoint_contacts_enabled$FUNC
    );
    static final FunctionDescriptor RprGenericJoint_coupled_axes$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprGenericJoint_coupled_axes$MH = RuntimeHelper.downcallHandle(
        "RprGenericJoint_coupled_axes",
        constants$39.RprGenericJoint_coupled_axes$FUNC
    );
}


