// Generated by jextract

package rapier.sys;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct RprArenaKey RprRigidBodyHandle;
 * }
 */
public final class RprRigidBodyHandle extends RprArenaKey {

    // Suppresses default constructor, ensuring non-instantiability.
    private RprRigidBodyHandle() {}
}


