// Generated by jextract

package rapier.sys_dim3_f64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final FunctionDescriptor RprColliderBuilder_build$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_build$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_build",
        constants$19.RprColliderBuilder_build$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_cuboid$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_cuboid$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_cuboid",
        constants$19.RprColliderBuilder_cuboid$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_drop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_drop$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_drop",
        constants$19.RprColliderBuilder_drop$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_restitution$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_restitution$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_restitution",
        constants$19.RprColliderBuilder_restitution$FUNC
    );
    static final FunctionDescriptor RprColliderSet_drop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderSet_drop$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_drop",
        constants$19.RprColliderSet_drop$FUNC
    );
    static final FunctionDescriptor RprColliderSet_index$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("index"),
            Constants$root.C_INT$LAYOUT.withName("generation")
        ).withName("RprColliderHandle")
    );
    static final MethodHandle RprColliderSet_index$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_index",
        constants$19.RprColliderSet_index$FUNC
    );
}


