// Generated by jextract

package rapier.sys_dim3_f64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor RprColliderBuilder_solver_groups$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("memberships"),
            Constants$root.C_INT$LAYOUT.withName("filter")
        ).withName("RprInteractionGroups")
    );
    static final MethodHandle RprColliderBuilder_solver_groups$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_solver_groups",
        constants$22.RprColliderBuilder_solver_groups$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_translation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_DOUBLE$LAYOUT.withName("x"),
            Constants$root.C_DOUBLE$LAYOUT.withName("y"),
            Constants$root.C_DOUBLE$LAYOUT.withName("z")
        ).withName("RprVector")
    );
    static final MethodHandle RprColliderBuilder_translation$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_translation",
        constants$22.RprColliderBuilder_translation$FUNC
    );
    static final FunctionDescriptor RprColliderMaterial_default$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_DOUBLE$LAYOUT.withName("friction"),
        Constants$root.C_DOUBLE$LAYOUT.withName("restitution"),
        Constants$root.C_INT$LAYOUT.withName("friction_combine_rule"),
        Constants$root.C_INT$LAYOUT.withName("restitution_combine_rule")
    ).withName("RprColliderMaterial"));
    static final MethodHandle RprColliderMaterial_default$MH = RuntimeHelper.downcallHandle(
        "RprColliderMaterial_default",
        constants$22.RprColliderMaterial_default$FUNC
    );
    static final FunctionDescriptor RprColliderSet_all$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderSet_all$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_all",
        constants$22.RprColliderSet_all$FUNC
    );
    static final FunctionDescriptor RprColliderSet_all_enabled$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderSet_all_enabled$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_all_enabled",
        constants$22.RprColliderSet_all_enabled$FUNC
    );
    static final FunctionDescriptor RprColliderSet_contains$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("index"),
            Constants$root.C_INT$LAYOUT.withName("generation")
        ).withName("RprArenaKey")
    );
    static final MethodHandle RprColliderSet_contains$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_contains",
        constants$22.RprColliderSet_contains$FUNC
    );
}


