// Generated by jextract

package rapier.sys_dim3_f64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class RprAngVector {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_DOUBLE$LAYOUT.withName("x"),
        Constants$root.C_DOUBLE$LAYOUT.withName("y"),
        Constants$root.C_DOUBLE$LAYOUT.withName("z")
    ).withName("RprAngVector");
    public static MemoryLayout $LAYOUT() {
        return RprAngVector.$struct$LAYOUT;
    }
    static final VarHandle x$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("x"));
    public static VarHandle x$VH() {
        return RprAngVector.x$VH;
    }
    public static double x$get(MemorySegment seg) {
        return (double)RprAngVector.x$VH.get(seg);
    }
    public static void x$set( MemorySegment seg, double x) {
        RprAngVector.x$VH.set(seg, x);
    }
    public static double x$get(MemorySegment seg, long index) {
        return (double)RprAngVector.x$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, double x) {
        RprAngVector.x$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle y$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("y"));
    public static VarHandle y$VH() {
        return RprAngVector.y$VH;
    }
    public static double y$get(MemorySegment seg) {
        return (double)RprAngVector.y$VH.get(seg);
    }
    public static void y$set( MemorySegment seg, double x) {
        RprAngVector.y$VH.set(seg, x);
    }
    public static double y$get(MemorySegment seg, long index) {
        return (double)RprAngVector.y$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, double x) {
        RprAngVector.y$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle z$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("z"));
    public static VarHandle z$VH() {
        return RprAngVector.z$VH;
    }
    public static double z$get(MemorySegment seg) {
        return (double)RprAngVector.z$VH.get(seg);
    }
    public static void z$set( MemorySegment seg, double x) {
        RprAngVector.z$VH.set(seg, x);
    }
    public static double z$get(MemorySegment seg, long index) {
        return (double)RprAngVector.z$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void z$set(MemorySegment seg, long index, double x) {
        RprAngVector.z$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


