// Generated by jextract

package rapier.sys_dim3_f64;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct RprSpacialVector {
 *     double x;
 *     double y;
 *     double z;
 *     double w;
 *     double a;
 *     double b;
 * };
 * }
 */
public class RprSpacialVector {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_DOUBLE$LAYOUT.withName("x"),
        Constants$root.C_DOUBLE$LAYOUT.withName("y"),
        Constants$root.C_DOUBLE$LAYOUT.withName("z"),
        Constants$root.C_DOUBLE$LAYOUT.withName("w"),
        Constants$root.C_DOUBLE$LAYOUT.withName("a"),
        Constants$root.C_DOUBLE$LAYOUT.withName("b")
    ).withName("RprSpacialVector");
    public static MemoryLayout $LAYOUT() {
        return RprSpacialVector.$struct$LAYOUT;
    }
    static final VarHandle x$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("x"));
    public static VarHandle x$VH() {
        return RprSpacialVector.x$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double x;
     * }
     */
    public static double x$get(MemorySegment seg) {
        return (double)RprSpacialVector.x$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double x;
     * }
     */
    public static void x$set(MemorySegment seg, double x) {
        RprSpacialVector.x$VH.set(seg, x);
    }
    public static double x$get(MemorySegment seg, long index) {
        return (double)RprSpacialVector.x$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, double x) {
        RprSpacialVector.x$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle y$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("y"));
    public static VarHandle y$VH() {
        return RprSpacialVector.y$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double y;
     * }
     */
    public static double y$get(MemorySegment seg) {
        return (double)RprSpacialVector.y$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double y;
     * }
     */
    public static void y$set(MemorySegment seg, double x) {
        RprSpacialVector.y$VH.set(seg, x);
    }
    public static double y$get(MemorySegment seg, long index) {
        return (double)RprSpacialVector.y$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, double x) {
        RprSpacialVector.y$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle z$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("z"));
    public static VarHandle z$VH() {
        return RprSpacialVector.z$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double z;
     * }
     */
    public static double z$get(MemorySegment seg) {
        return (double)RprSpacialVector.z$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double z;
     * }
     */
    public static void z$set(MemorySegment seg, double x) {
        RprSpacialVector.z$VH.set(seg, x);
    }
    public static double z$get(MemorySegment seg, long index) {
        return (double)RprSpacialVector.z$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void z$set(MemorySegment seg, long index, double x) {
        RprSpacialVector.z$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle w$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("w"));
    public static VarHandle w$VH() {
        return RprSpacialVector.w$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double w;
     * }
     */
    public static double w$get(MemorySegment seg) {
        return (double)RprSpacialVector.w$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double w;
     * }
     */
    public static void w$set(MemorySegment seg, double x) {
        RprSpacialVector.w$VH.set(seg, x);
    }
    public static double w$get(MemorySegment seg, long index) {
        return (double)RprSpacialVector.w$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void w$set(MemorySegment seg, long index, double x) {
        RprSpacialVector.w$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle a$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("a"));
    public static VarHandle a$VH() {
        return RprSpacialVector.a$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double a;
     * }
     */
    public static double a$get(MemorySegment seg) {
        return (double)RprSpacialVector.a$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double a;
     * }
     */
    public static void a$set(MemorySegment seg, double x) {
        RprSpacialVector.a$VH.set(seg, x);
    }
    public static double a$get(MemorySegment seg, long index) {
        return (double)RprSpacialVector.a$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void a$set(MemorySegment seg, long index, double x) {
        RprSpacialVector.a$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle b$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("b"));
    public static VarHandle b$VH() {
        return RprSpacialVector.b$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double b;
     * }
     */
    public static double b$get(MemorySegment seg) {
        return (double)RprSpacialVector.b$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double b;
     * }
     */
    public static void b$set(MemorySegment seg, double x) {
        RprSpacialVector.b$VH.set(seg, x);
    }
    public static double b$get(MemorySegment seg, long index) {
        return (double)RprSpacialVector.b$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void b$set(MemorySegment seg, long index, double x) {
        RprSpacialVector.b$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


