// Generated by jextract

package rapier.sys_dim3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final FunctionDescriptor RprContactPair_collider1$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("index"),
        Constants$root.C_INT$LAYOUT.withName("generation")
    ).withName("RprArenaKey"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_collider1$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_collider1",
        constants$39.RprContactPair_collider1$FUNC
    );
    static final FunctionDescriptor RprContactPair_collider2$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("index"),
        Constants$root.C_INT$LAYOUT.withName("generation")
    ).withName("RprArenaKey"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_collider2$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_collider2",
        constants$39.RprContactPair_collider2$FUNC
    );
    static final FunctionDescriptor RprContactPair_has_any_active_contact$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_has_any_active_contact$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_has_any_active_contact",
        constants$39.RprContactPair_has_any_active_contact$FUNC
    );
    static final FunctionDescriptor RprContactPair_manifolds$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactPair_manifolds$MH = RuntimeHelper.downcallHandle(
        "RprContactPair_manifolds",
        constants$39.RprContactPair_manifolds$FUNC
    );
    static final FunctionDescriptor RprDynamicRayCastVehicleController_add_wheel$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_FLOAT$LAYOUT.withName("x"),
            Constants$root.C_FLOAT$LAYOUT.withName("y"),
            Constants$root.C_FLOAT$LAYOUT.withName("z")
        ).withName("RprVector"),
        MemoryLayout.structLayout(
            Constants$root.C_FLOAT$LAYOUT.withName("x"),
            Constants$root.C_FLOAT$LAYOUT.withName("y"),
            Constants$root.C_FLOAT$LAYOUT.withName("z")
        ).withName("RprVector"),
        MemoryLayout.structLayout(
            Constants$root.C_FLOAT$LAYOUT.withName("x"),
            Constants$root.C_FLOAT$LAYOUT.withName("y"),
            Constants$root.C_FLOAT$LAYOUT.withName("z")
        ).withName("RprVector"),
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_FLOAT$LAYOUT.withName("suspension_stiffness"),
            Constants$root.C_FLOAT$LAYOUT.withName("suspension_compression"),
            Constants$root.C_FLOAT$LAYOUT.withName("suspension_damping"),
            Constants$root.C_FLOAT$LAYOUT.withName("max_suspension_travel"),
            Constants$root.C_FLOAT$LAYOUT.withName("friction_slip"),
            Constants$root.C_FLOAT$LAYOUT.withName("max_suspension_force")
        ).withName("RprWheelTuning")
    );
    static final MethodHandle RprDynamicRayCastVehicleController_add_wheel$MH = RuntimeHelper.downcallHandle(
        "RprDynamicRayCastVehicleController_add_wheel",
        constants$39.RprDynamicRayCastVehicleController_add_wheel$FUNC
    );
    static final FunctionDescriptor RprDynamicRayCastVehicleController_chassis$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("index"),
        Constants$root.C_INT$LAYOUT.withName("generation")
    ).withName("RprArenaKey"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprDynamicRayCastVehicleController_chassis$MH = RuntimeHelper.downcallHandle(
        "RprDynamicRayCastVehicleController_chassis",
        constants$39.RprDynamicRayCastVehicleController_chassis$FUNC
    );
}


