// Generated by jextract

package rapier.sys_dim2_f32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final FunctionDescriptor RprContactManifold_solver_flags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactManifold_solver_flags$MH = RuntimeHelper.downcallHandle(
        "RprContactManifold_solver_flags",
        constants$36.RprContactManifold_solver_flags$FUNC
    );
    static final FunctionDescriptor RprContactManifold_subshape1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactManifold_subshape1$MH = RuntimeHelper.downcallHandle(
        "RprContactManifold_subshape1",
        constants$36.RprContactManifold_subshape1$FUNC
    );
    static final FunctionDescriptor RprContactManifold_subshape2$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactManifold_subshape2$MH = RuntimeHelper.downcallHandle(
        "RprContactManifold_subshape2",
        constants$36.RprContactManifold_subshape2$FUNC
    );
    static final FunctionDescriptor RprContactManifold_subshape_pos1$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactManifold_subshape_pos1$MH = RuntimeHelper.downcallHandle(
        "RprContactManifold_subshape_pos1",
        constants$36.RprContactManifold_subshape_pos1$FUNC
    );
    static final FunctionDescriptor RprContactManifold_subshape_pos2$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactManifold_subshape_pos2$MH = RuntimeHelper.downcallHandle(
        "RprContactManifold_subshape_pos2",
        constants$36.RprContactManifold_subshape_pos2$FUNC
    );
    static final FunctionDescriptor RprContactManifold_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprContactManifold_user_data$MH = RuntimeHelper.downcallHandle(
        "RprContactManifold_user_data",
        constants$36.RprContactManifold_user_data$FUNC
    );
}


