// Generated by jextract

package rapier.sys;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * _Bool (*RprQueryPipeline_intersections_with_shape$callback)(struct RprArenaKey);
 * }
 */
public interface RprQueryPipeline_intersections_with_shape$callback {

    boolean apply(java.lang.foreign.MemorySegment _x0);
    static MemorySegment allocate(RprQueryPipeline_intersections_with_shape$callback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(RprQueryPipeline_intersections_with_shape$callback.class, fi, constants$60.RprQueryPipeline_intersections_with_shape$callback$FUNC, scope);
    }
    static RprQueryPipeline_intersections_with_shape$callback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment __x0) -> {
            try {
                return (boolean)constants$60.RprQueryPipeline_intersections_with_shape$callback$MH.invokeExact(symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


