// Generated by jextract

package rapier.sys_dim3_f32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$91 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$91() {}
    static final FunctionDescriptor RprSolverContact_tangent_velocity$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_FLOAT$LAYOUT.withName("x"),
        Constants$root.C_FLOAT$LAYOUT.withName("y"),
        Constants$root.C_FLOAT$LAYOUT.withName("z")
    ).withName("RprVector"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprSolverContact_tangent_velocity$MH = RuntimeHelper.downcallHandle(
        "RprSolverContact_tangent_velocity",
        constants$91.RprSolverContact_tangent_velocity$FUNC
    );
    static final FunctionDescriptor RprVHACDParameters_default$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_FLOAT$LAYOUT.withName("concavity"),
        Constants$root.C_FLOAT$LAYOUT.withName("alpha"),
        Constants$root.C_FLOAT$LAYOUT.withName("beta"),
        Constants$root.C_INT$LAYOUT.withName("resolution"),
        Constants$root.C_INT$LAYOUT.withName("plane_downsampling"),
        Constants$root.C_INT$LAYOUT.withName("convex_hull_downsampling"),
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("tag"),
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    Constants$root.C_BOOL$LAYOUT.withName("detect_cavities")
                ).withName("flood_fill")
            ).withName("union (anonymous at /home/socket/Projects/rapier-ffi/rapier-java/rapier-java-sys/build/librapier.h:1334:3)"),
            MemoryLayout.paddingLayout(24)
        ).withName("fill_mode"),
        Constants$root.C_BOOL$LAYOUT.withName("convex_hull_approximation"),
        MemoryLayout.paddingLayout(24),
        Constants$root.C_INT$LAYOUT.withName("max_convex_hulls")
    ).withName("RprVHACDParameters"));
    static final MethodHandle RprVHACDParameters_default$MH = RuntimeHelper.downcallHandle(
        "RprVHACDParameters_default",
        constants$91.RprVHACDParameters_default$FUNC
    );
    static final FunctionDescriptor RprVHACD_decompose$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle RprVHACD_decompose$MH = RuntimeHelper.downcallHandle(
        "RprVHACD_decompose",
        constants$91.RprVHACD_decompose$FUNC
    );
    static final FunctionDescriptor RprVHACD_drop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprVHACD_drop$MH = RuntimeHelper.downcallHandle(
        "RprVHACD_drop",
        constants$91.RprVHACD_drop$FUNC
    );
    static final FunctionDescriptor RprWheelTuning_default$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_FLOAT$LAYOUT.withName("suspension_stiffness"),
        Constants$root.C_FLOAT$LAYOUT.withName("suspension_compression"),
        Constants$root.C_FLOAT$LAYOUT.withName("suspension_damping"),
        Constants$root.C_FLOAT$LAYOUT.withName("max_suspension_travel"),
        Constants$root.C_FLOAT$LAYOUT.withName("friction_slip"),
        Constants$root.C_FLOAT$LAYOUT.withName("max_suspension_force")
    ).withName("RprWheelTuning"));
    static final MethodHandle RprWheelTuning_default$MH = RuntimeHelper.downcallHandle(
        "RprWheelTuning_default",
        constants$91.RprWheelTuning_default$FUNC
    );
    static final FunctionDescriptor RprWheel_axle$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_FLOAT$LAYOUT.withName("x"),
        Constants$root.C_FLOAT$LAYOUT.withName("y"),
        Constants$root.C_FLOAT$LAYOUT.withName("z")
    ).withName("RprVector"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprWheel_axle$MH = RuntimeHelper.downcallHandle(
        "RprWheel_axle",
        constants$91.RprWheel_axle$FUNC
    );
}


