// Generated by jextract

package rapier.sys_dim3_f32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$22 {

    static final FunctionDescriptor RprColliderSet_all$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderSet_all$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_all",
        constants$22.RprColliderSet_all$FUNC
    );
    static final FunctionDescriptor RprColliderSet_all_enabled$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderSet_all_enabled$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_all_enabled",
        constants$22.RprColliderSet_all_enabled$FUNC
    );
    static final FunctionDescriptor RprColliderSet_contains$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("index"),
            Constants$root.C_INT$LAYOUT.withName("generation")
        ).withName("RprArenaKey")
    );
    static final MethodHandle RprColliderSet_contains$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_contains",
        constants$22.RprColliderSet_contains$FUNC
    );
    static final FunctionDescriptor RprColliderSet_drop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderSet_drop$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_drop",
        constants$22.RprColliderSet_drop$FUNC
    );
    static final FunctionDescriptor RprColliderSet_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("index"),
            Constants$root.C_INT$LAYOUT.withName("generation")
        ).withName("RprArenaKey")
    );
    static final MethodHandle RprColliderSet_get$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_get",
        constants$22.RprColliderSet_get$FUNC
    );
    static final FunctionDescriptor RprColliderSet_get_mut$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("index"),
            Constants$root.C_INT$LAYOUT.withName("generation")
        ).withName("RprArenaKey")
    );
    static final MethodHandle RprColliderSet_get_mut$MH = RuntimeHelper.downcallHandle(
        "RprColliderSet_get_mut",
        constants$22.RprColliderSet_get_mut$FUNC
    );
}


