// Generated by jextract

package rapier.sys_dim3_f32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$95 {

    static final FunctionDescriptor RprWheel_set_max_suspension_travel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle RprWheel_set_max_suspension_travel$MH = RuntimeHelper.downcallHandle(
        "RprWheel_set_max_suspension_travel",
        constants$95.RprWheel_set_max_suspension_travel$FUNC
    );
    static final FunctionDescriptor RprWheel_set_radius$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle RprWheel_set_radius$MH = RuntimeHelper.downcallHandle(
        "RprWheel_set_radius",
        constants$95.RprWheel_set_radius$FUNC
    );
    static final FunctionDescriptor RprWheel_set_rotation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle RprWheel_set_rotation$MH = RuntimeHelper.downcallHandle(
        "RprWheel_set_rotation",
        constants$95.RprWheel_set_rotation$FUNC
    );
    static final FunctionDescriptor RprWheel_set_side_impulse$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle RprWheel_set_side_impulse$MH = RuntimeHelper.downcallHandle(
        "RprWheel_set_side_impulse",
        constants$95.RprWheel_set_side_impulse$FUNC
    );
    static final FunctionDescriptor RprWheel_set_steering$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle RprWheel_set_steering$MH = RuntimeHelper.downcallHandle(
        "RprWheel_set_steering",
        constants$95.RprWheel_set_steering$FUNC
    );
    static final FunctionDescriptor RprWheel_set_suspension_rest_length$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle RprWheel_set_suspension_rest_length$MH = RuntimeHelper.downcallHandle(
        "RprWheel_set_suspension_rest_length",
        constants$95.RprWheel_set_suspension_rest_length$FUNC
    );
}


