// Generated by jextract

package rapier.sys_dim3_f32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$19 {

    static final FunctionDescriptor RprCCDSolver_drop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprCCDSolver_drop$MH = RuntimeHelper.downcallHandle(
        "RprCCDSolver_drop",
        constants$19.RprCCDSolver_drop$FUNC
    );
    static final FunctionDescriptor RprCCDSolver_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle RprCCDSolver_new$MH = RuntimeHelper.downcallHandle(
        "RprCCDSolver_new",
        constants$19.RprCCDSolver_new$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_active_collision_types$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_active_collision_types$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_active_collision_types",
        constants$19.RprColliderBuilder_active_collision_types$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_active_events$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_active_events$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_active_events",
        constants$19.RprColliderBuilder_active_events$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_active_hooks$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_active_hooks$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_active_hooks",
        constants$19.RprColliderBuilder_active_hooks$FUNC
    );
    static final FunctionDescriptor RprColliderBuilder_build$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RprColliderBuilder_build$MH = RuntimeHelper.downcallHandle(
        "RprColliderBuilder_build",
        constants$19.RprColliderBuilder_build$FUNC
    );
}


