name: Build Java

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # TODO: Ubuntu 20.04 has libc 2.31. We want to target CentOS 7, with libc 2.17 (minimum Rust ver.)
        os: [ubuntu-20.04, windows-latest, macos-latest]
        dimension: [dim2, dim3]
        precision: [f32, f64]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2
    - name: Build
      run: |
        cd rapier-java
        ./gradlew --stacktrace --info -PbuildProfile=release build
