name: Build Java

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v3
    - name: Add build targets
      run: |
        rustup target add aarch64-unknown-linux-gnu
        sudo yum install gcc-aarch64-linux-gnu
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        
    - uses: gradle/gradle-build-action@v2
    - name: Build
      run: |
        cd rapier-java
        ./gradlew --stacktrace --info -PbuildProfile=release build
