name: Publish Java

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dimension: [dim2, dim3]
        precision: [f32, f64]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
    - uses: gradle/gradle-build-action@v2
    - name: Build
      run: |
        cd rapier-java
        ./gradlew --stacktrace --info -PbuildProfile=release build
    - name: Get version type
      run: |
        VERSION_TYPE=$(./gradlew -q --console=plain --no-daemon printVersionType)
        echo VERSION_TYPE=$VERSION_TYPE
        echo VERSION_TYPE=$VERSION_TYPE >> $GITHUB_ENV
    - name: Publish snapshot
      if: ${{ env.VERSION_TYPE == 'snapshot' }}
      run: |
        ./gradlew publish
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Publish release
      if: ${{ env.VERSION_TYPE == 'release' }}
      run: |
        ./gradlew -PforceSign=true publishToSonatype closeSonatypeStagingRepository
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenSigningKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_mavenSigningPassword: ${{ secrets.SIGNING_PASSWORD }}
